language: node_js
os:
  - linux
  - windows
  - osx
node_js:
  - 10
  - lts/*
  - node
env:
  - YARN_GPG=no

script:
  - yarn lint
  - yarn test --coverage
  - yarn build
  - bash <(curl -s https://codecov.io/bash)

before_deploy: cd pkg
after_deploy: cd ..
deploy:
  - provider: npm
    edge: true
    on:
      tags: true
      os: linux
      node: lts/*
  - provider: npm
    edge:
      branch: master
    registry: https://npm.pkg.github.com/@kripod
    api_token: $GPR_API_TOKEN
    on:
      tags: true
      os: linux
      node: lts/*
