name: Node CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: ${{ matrix.node_version }}
      - run: |
          yarn
          yarn test
        env:
          CI: true
