language: node_js
os:
  - linux
  - windows
  - osx
node_js:
  - 10
  - lts/*
  - node

script:
  - yarn lint
  - yarn test --coverage
  - yarn build

before_deploy: cd pkg
deploy:
  - provider: npm
    edge: true
    on:
      tags: true
  - provider: npm
    edge: true
    registry: https://npm.pkg.github.com/@kripod
    api_token: $GPR_API_TOKEN
    on:
      tags: true
