language: node_js
os:
  - linux
  - windows
  - osx
node_js:
  - 10
  - lts/*
  - node
env:
  - YARN_GPG=no

script:
  - yarn lint
  - yarn build
  - yarn test --coverage
  - bash <(curl -s https://codecov.io/bash)

# TODO: Remove temporary fix for GPR
before_deploy: cd pkg
after_deploy: echo 'registry=https://npm.pkg.github.com/@kripod' > .npmrc && cd ..
deploy:
  - provider: npm
    edge: true
    on:
      tags: true
      os: linux
      node: lts/*
  - provider: npm
    edge: true
    registry: https://npm.pkg.github.com
    api_token: $GPR_API_TOKEN
    on:
      tags: true
      os: linux
      node: lts/*
