name: Node CI
on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-latest] # TODO: windows-latest, macOS-latest with Codecov

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: ${{ matrix.node }}
      - run: |
          yarn
          yarn lint
          yarn test --coverage
        env:
          CI: true
      - uses: codecov/codecov-action@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish-npm:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          registry-url: https://registry.npmjs.org
      - run: |
          yarn
          yarn build
      - run: yarn publish pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  # publish-gpr:
  #   needs: lint-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-node@master
  #       with:
  #         registry-url: https://npm.pkg.github.com
  #     - run: |
  #         yarn
  #         yarn build
  #     - run: yarn publish pkg
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
